services:
  - type: web
    name: medical-pos-frontend
    runtime: static
    repo: https://github.com/waqar-nawaz/Medical-pos.git
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/renderer/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate